Mesd\SettingsBundle\Entity\Cluster:
    type: entity
    table: setting_cluster
    repositoryClass: Mesd\SettingsBundle\Repository\ClusterRepository
    fields:
        id:
            type: integer
            id: true
            generator:
                strategy: AUTO
        name:
            type: string
            length: 64
            nullable: false
        description:
            type: text
            nullable: true
        setting:
            column: setting
            type: array
            nullable: true

    manyToOne:
        hive:
            targetEntity: Hive
            inversedBy: cluster
            joinColumn:
                name: hive_id
                referencedColumnName: id

    uniqueConstraints:
        setting_cluster_hive_name_ukey:
            columns: [ hive_id, name ]

    lifecycleCallbacks: {  }