<?php

namespace Fc\SettingsBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * HiveRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class HiveRepository extends EntityRepository
{
}